apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common
  - clusterinstance.yaml

namespace: ocp1m0w-a

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: ocp1m0w-a
  target:
    kind: Namespace
    name: CLUSTER_ID

- patch: |-
    - op: replace
      path: /metadata/name
      value: ocp1m0w-a-cr
  target:
    kind: ClusterRoleBinding
    name: CLUSTER_ID-cr
