# this is helm chart values.yaml, which will create argocd 'projects' + 'applications'      

default:
  project:
 
  app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
    finalizers:
      - resources-finalizer.argocd.argoproj.io  
    enabled: true
    enableAutoSync: true
    autoSyncPrune: false
    project: acm-clusters
    labels:
      app-source: cluster-hub
      repo: acm-clusters
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/AsherShoshan/openshift-virtualization-gitops
      targetRevision: main
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true  
    - FailOnSharedResource=true
    - RespectIgnoreDifferences=true
    - CreateNamespace=false
    syncPolicyRetry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy


projects:
  acm-clusters:
    annotations:
      project: acm-clusters
    labels:
      project: acm-clusters
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    - '*'
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
# projects: {}

applications:
  ocp-edge1:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-gitops
    source:
      path: clusters/hub12-3/managed-clusters/ocp-edge1
  
  # ocp-edge1-cl4:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '5'
  #   destination:
  #     namespace: openshift-gitops
  #   source:
  #     path: clusters/hub12-3/managed-clusters/ocp-edge1-cl4
