apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common
  - clusterinstance.yaml

namespace: ocp-edge1

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: ocp-edge1
  target:
    kind: Namespace
    name: CLUSTER_ID

- patch: |-
    - op: replace
      path: /metadata/name
      value: ocp-edge1-cr
  target:
    kind: ClusterRoleBinding
    name: CLUSTER_ID-cr
